remove local 'beta' tag during builds

diff --git a/.github/workflows/build-appimage.yml b/.github/workflows/build-appimage.yml
--- a/.github/workflows/build-appimage.yml
+++ b/.github/workflows/build-appimage.yml
@@ -21,6 +21,7 @@ jobs:
     - name: Get Git tag description
       id: git_info
       run: |
+        git tag -d beta 2>/dev/null || echo "Tag 'beta' not found"
         echo "GIT_TAG=$(git describe --tags --always --long)" >> $GITHUB_ENV
 
     - name: Install Build Dependencies
